# Generated by Django 4.2.1 on 2023-09-30 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0004_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
