# Generated by Django 4.2.1 on 2023-09-30 18:08

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_customuser_user_delete_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, validators=[accounts.models.PasswordValidator()]),
        ),
    ]
